# Generated by Django 4.0.6 on 2022-07-28 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_integer', models.IntegerField(blank=True, null=True)),
                ('the_pos_integer', models.PositiveIntegerField(blank=True, null=True)),
                ('the_float', models.FloatField(blank=True, null=True)),
                ('the_json', models.JSONField(blank=True, null=True)),
                ('the_boolean', models.BooleanField(blank=True, null=True)),
                ('the_char', models.CharField(blank=True, max_length=200, null=True)),
                ('the_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('the_time', models.TimeField(blank=True, null=True)),
                ('the_date', models.DateField(blank=True, null=True)),
                ('the_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('the_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('the_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('the_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
